[package]
name = "memstore"
version = "0.1.0"
description = "An in-memory implementation of the `async-raft::RaftStorage` trait."
license = "MIT/Apache-2.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
async-raft = { version="0.5", path="../async-raft" }
serde = { version="1.0.114", features=["derive"] }
serde_json = "1.0.57"
thiserror = "1.0.20"
tokio = { version="0.2.22", default-features=false, features=["sync"] }
tracing = "0.1.17"
tracing-futures = "0.2.4"
